import {useEffect,useState} from 'react';
import {FaRegNewspaper} from 'react-icons/fa';
import {MdNavigateBefore} from 'react-icons/md';
import {publicArticlesApi,type PublicArticle} from '@/services/publicArticlesApi';
import BlogCard from './BlogCard';
import { motion } from '@/components/Motion';
export default function BlogPreview(){
    const [items,setItems]=useState<PublicArticle[]>([]);
    useEffect(()=>{let active=true;void publicArticlesApi.list().then(result=>{if(active)setItems(result.items.slice(0,3));}).catch(()=>{});return()=>{active=false;};},[]);
    return <section id="articles" className="relative bg-[#f5f7fd] z-0 px-5 pt-12 pb-20 text-gray-900 md:px-10"><motion.img initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} transition={{duration:1.5,type:'spring',bounce:0.1}} viewport={{once:true}} className="absolute right-25 bottom-25 z-0 hidden lg:block blur-xl" src="/img/services/cloud-1.webp" alt="" aria-hidden="true" loading="lazy"/><motion.img initial={{opacity:0,y:-40}} whileInView={{opacity:1,y:0}} transition={{duration:1.5,type:'spring',bounce:0.1}} viewport={{once:true}} className="absolute left-25 top-25 z-0 hidden lg:block blur-xl" src="/img/services/cloud-2.webp" alt="" aria-hidden="true" loading="lazy"/><img className="absolute -bottom-7 left-0 z-0 hidden lg:block" src="/img/services/dashed-line-up.png" alt="" loading="lazy"/>
        <div className="relative mx-auto max-w-7xl"><div className="mb-6 flex flex-col items-center gap-3 text-center"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} transition={{duration:1.5,type:'spring',bounce:0.4}} viewport={{once:true}} className="rounded-full border border-secondary p-0.5"><div className="bg-linear-to-br from-powderblue to-duskblue rounded-full border border-secondary p-4"><FaRegNewspaper size={32} color="white"/></div></motion.div><motion.h2 initial={{opacity:0,y:-40}} whileInView={{opacity:1,y:0}} transition={{duration:1.5,type:'spring',bounce:0.5}} viewport={{once:true}} className="font-dana text-3xl text-primary md:text-5xl">تازه‌ترین مقالات ENT</motion.h2><motion.p initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} transition={{duration:1.5,type:'spring',bounce:0.4}} viewport={{once:true}} className="max-w-2xl text-gray-600">پاسخ‌های ساده و مستند به پرسش‌های رایج درباره سلامت گوش، بینی، سینوس، گلو و رینوپلاستی</motion.p></div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">{items.map((item,index)=><motion.div key={item.id} className="h-full" initial={{opacity:0,y:50}} whileInView={{opacity:1,y:0}} transition={{duration:1.2,type:'spring',bounce:0.2,delay:index*0.15}} viewport={{once:true}}><BlogCard article={item}/></motion.div>)}</div>{!items.length&&<p className="text-center text-gray-600">هنوز مقاله‌ای برای نمایش منتشر نشده است.</p>}<motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} transition={{duration:1.2,type:'spring',bounce:0.3}} viewport={{once:true}} className="mt-12 flex justify-center"><a href="/articles/" className="group flex items-center gap-1 rounded-lg bg-primary px-5 py-3 text-white shadow-lg transition duration-300 hover:-translate-y-1 hover:bg-primary-deep hover:shadow-xl">مشاهده همه مقالات<MdNavigateBefore size={22}/></a></motion.div></div>
    </section>;
}
